--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      UNAM
-- Project :      AUTOS-JRCBD_S1.DM1
-- Author :       Jorge
--
-- Date Created : Monday, April 20, 2020 16:25:55
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: F_JRC_AGENCIA_1 
--

CREATE TABLE F_JRC_AGENCIA_1(
    AGENCIA_ID          NUMBER(10, 0)    NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    CLAVE               VARCHAR2(8)      NOT NULL,
    AGENCIA_ANEXA_ID    NUMBER(10, 0),
    CONSTRAINT F_JRC_AGENCIA_1_PK PRIMARY KEY (AGENCIA_ID)
)
;



-- 
-- TABLE: F_JRC_AUTO_1 
--

CREATE TABLE F_JRC_AUTO_1(
    AUTO_ID    NUMBER(10, 0)    NOT NULL,
    PRECIO     NUMBER(9, 2)     NOT NULL,
    FOTO       BLOB             NOT NULL,
    CONSTRAINT F_JRC_AUTO_F1_PK PRIMARY KEY (AUTO_ID)
)
;



-- 
-- TABLE: F_JRC_AUTO_3 
--

CREATE TABLE F_JRC_AUTO_3(
    AUTO_ID       NUMBER(10, 0)    NOT NULL,
    MARCA         VARCHAR2(40)     NOT NULL,
    MODELO        VARCHAR2(40)     NOT NULL,
    ANIO          NUMBER(4, 0)     NOT NULL,
    NUM_SERIE     VARCHAR2(20)     NOT NULL,
    TIPO          CHAR(1)          NOT NULL,
    DESCUENTO     NUMBER(9, 2),
    AGENCIA_ID    NUMBER(10, 0)    NOT NULL,
    CLIENTE_ID    NUMBER(10, 0),
    CONSTRAINT F_JRC_AUTO_3_PK PRIMARY KEY (AUTO_ID), 
    CONSTRAINT AUTO_3_AGENCIA_1_ID_FK FOREIGN KEY (AGENCIA_ID)
    REFERENCES F_JRC_AGENCIA_1(AGENCIA_ID)
)
;



-- 
-- TABLE: F_JRC_AUTO_PARTICULAR_1 
--

CREATE TABLE F_JRC_AUTO_PARTICULAR_1(
    AUTO_ID          NUMBER(10, 0)    NOT NULL,
    NUM_CILINDROS    NUMBER(1, 0)     NOT NULL,
    NUM_PASAJEROS    NUMBER(2, 0)     NOT NULL,
    CLASE            CHAR(1)          NOT NULL,
    CONSTRAINT F_JRC_AUTO_PARTICULAR_1_PK PRIMARY KEY (AUTO_ID), 
    CONSTRAINT AUTO_PARTICULAR_1_AUTO_3_ID_FK FOREIGN KEY (AUTO_ID)
    REFERENCES F_JRC_AUTO_3(AUTO_ID)
)
;



