insert into pais(pais_id,nombre,clave,continente) values (1,'Anguila','AIA','AME');
insert into pais(pais_id,nombre,clave,continente) values (2,'Antigua y Barbuda','ATG','AME');
insert into pais(pais_id,nombre,clave,continente) values (3,'Argentina','ARG','AME');
insert into pais(pais_id,nombre,clave,continente) values (4,'Aruba','ABW','AME');
insert into pais(pais_id,nombre,clave,continente) values (5,'Bahamas','BHS','AME');
insert into pais(pais_id,nombre,clave,continente) values (6,'Barbados','BRB','AME');
insert into pais(pais_id,nombre,clave,continente) values (7,'Belice','BLZ','AME');
insert into pais(pais_id,nombre,clave,continente) values (8,'Bermudas','BMU','AME');
insert into pais(pais_id,nombre,clave,continente) values (9,'Bolivia','BOL','AME');
insert into pais(pais_id,nombre,clave,continente) values (10,'Bonaire','BES','AME');
insert into pais(pais_id,nombre,clave,continente) values (11,'Brasil','BRA','AME');
insert into pais(pais_id,nombre,clave,continente) values (12,'Canadá','CAN','AME');
insert into pais(pais_id,nombre,clave,continente) values (13,'Chile','CHL','AME');
insert into pais(pais_id,nombre,clave,continente) values (14,'Colombia','COL','AME');
insert into pais(pais_id,nombre,clave,continente) values (15,'Costa Rica','CRI','AME');
insert into pais(pais_id,nombre,clave,continente) values (16,'Cuba','CUB','AME');
insert into pais(pais_id,nombre,clave,continente) values (17,'Curazao','CUW','AME');
insert into pais(pais_id,nombre,clave,continente) values (18,'Dominica','DMA','AME');
insert into pais(pais_id,nombre,clave,continente) values (19,'Ecuador','ECU','AME');
insert into pais(pais_id,nombre,clave,continente) values (20,'El Salvador','SLV','AME');
insert into pais(pais_id,nombre,clave,continente) values (21,'Estados Unidos','USA','AME');
insert into pais(pais_id,nombre,clave,continente) values (22,'Granada','GRD','AME');
insert into pais(pais_id,nombre,clave,continente) values (23,'Groenlandia','GRL','AME');
insert into pais(pais_id,nombre,clave,continente) values (24,'Guadalupe','GLP','AME');
insert into pais(pais_id,nombre,clave,continente) values (25,'Guatemala','GTM','AME');
insert into pais(pais_id,nombre,clave,continente) values (26,'Guayana Francesa','GUF','AME');
insert into pais(pais_id,nombre,clave,continente) values (27,'Guyana','GUY','AME');
insert into pais(pais_id,nombre,clave,continente) values (28,'Haití','HTI','AME');
insert into pais(pais_id,nombre,clave,continente) values (29,'Honduras','HND','AME');
insert into pais(pais_id,nombre,clave,continente) values (30,'Islas Caimán','CYM','AME');
insert into pais(pais_id,nombre,clave,continente) values (31,'Islas Falkland (Malvinas)','FLK','AME');
insert into pais(pais_id,nombre,clave,continente) values (32,'Islas Turcas y Caicos','TCA','AME');
insert into pais(pais_id,nombre,clave,continente) values (33,'Islas Virgenes Británicas','VGB','AME');
insert into pais(pais_id,nombre,clave,continente) values (34,'Islas Virgenes de Los Estados Unidos','VIR','AME');
insert into pais(pais_id,nombre,clave,continente) values (35,'Jamaica','JAM','AME');
insert into pais(pais_id,nombre,clave,continente) values (36,'Martinica','MTQ','AME');
insert into pais(pais_id,nombre,clave,continente) values (37,'México','MEX','AME');
insert into pais(pais_id,nombre,clave,continente) values (38,'Montserrat','MSR','AME');
insert into pais(pais_id,nombre,clave,continente) values (39,'Nicaragua','NIC','AME');
insert into pais(pais_id,nombre,clave,continente) values (40,'Panamá','PAN','AME');
insert into pais(pais_id,nombre,clave,continente) values (41,'Paraguay','PRY','AME');
insert into pais(pais_id,nombre,clave,continente) values (42,'Perú','PER','AME');
insert into pais(pais_id,nombre,clave,continente) values (43,'Puerto Rico','PRI','AME');
insert into pais(pais_id,nombre,clave,continente) values (44,'República Dominicana','DOM','AME');
insert into pais(pais_id,nombre,clave,continente) values (45,'San Bartolomé','BLM','AME');
insert into pais(pais_id,nombre,clave,continente) values (46,'San Cristóbal y Nieves','KNA','AME');
insert into pais(pais_id,nombre,clave,continente) values (47,'San Martín (Parte Francesa)','MAF','AME');
insert into pais(pais_id,nombre,clave,continente) values (48,'San Pedro y Miquelón','SPM','AME');
insert into pais(pais_id,nombre,clave,continente) values (49,'San Vicente y Las Granadinas','VCT','AME');
insert into pais(pais_id,nombre,clave,continente) values (50,'Santa Lucía','LCA','AME');
insert into pais(pais_id,nombre,clave,continente) values (51,'Sint Maarten (Parte Neerlandesa)','SXM','AME');
insert into pais(pais_id,nombre,clave,continente) values (52,'Surinam','SUR','AME');
insert into pais(pais_id,nombre,clave,continente) values (53,'Trinidad y Tobago','TTO','AME');
insert into pais(pais_id,nombre,clave,continente) values (54,'Uruguay','URY','AME');
insert into pais(pais_id,nombre,clave,continente) values (55,'Venezuela','VEN','AME');
insert into pais(pais_id,nombre,clave,continente) values (56,'Albania','ALB','EUR');
insert into pais(pais_id,nombre,clave,continente) values (57,'Alemania','DEU','EUR');
insert into pais(pais_id,nombre,clave,continente) values (58,'Andorra','AND','EUR');
insert into pais(pais_id,nombre,clave,continente) values (59,'Austria','AUT','EUR');
insert into pais(pais_id,nombre,clave,continente) values (60,'Bélgica','BEL','EUR');
insert into pais(pais_id,nombre,clave,continente) values (61,'Bielorrusia','BLR','EUR');
insert into pais(pais_id,nombre,clave,continente) values (62,'Bosnia y Herzegovina','BIH','EUR');
insert into pais(pais_id,nombre,clave,continente) values (63,'Bulgaria','BGR','EUR');
insert into pais(pais_id,nombre,clave,continente) values (64,'Croacia','HRV','EUR');
insert into pais(pais_id,nombre,clave,continente) values (65,'Dinamarca','DNK','EUR');
insert into pais(pais_id,nombre,clave,continente) values (66,'Eslovaquia','SVK','EUR');
insert into pais(pais_id,nombre,clave,continente) values (67,'Eslovenia','SVN','EUR');
insert into pais(pais_id,nombre,clave,continente) values (68,'España','ESP','EUR');
insert into pais(pais_id,nombre,clave,continente) values (69,'Estonia','EST','EUR');
insert into pais(pais_id,nombre,clave,continente) values (70,'Federacion Rusa','RUS','EUR');
insert into pais(pais_id,nombre,clave,continente) values (71,'Finlandia','FIN','EUR');
insert into pais(pais_id,nombre,clave,continente) values (72,'Francia','FRA','EUR');
insert into pais(pais_id,nombre,clave,continente) values (73,'Gibraltar','GIB','EUR');
insert into pais(pais_id,nombre,clave,continente) values (74,'Grecia','GRC','EUR');
insert into pais(pais_id,nombre,clave,continente) values (75,'Guernsey','GGY','EUR');
insert into pais(pais_id,nombre,clave,continente) values (76,'Hungría','HUN','EUR');
insert into pais(pais_id,nombre,clave,continente) values (77,'Irlanda','IRL','EUR');
insert into pais(pais_id,nombre,clave,continente) values (78,'Isla de Man','IMN','EUR');
insert into pais(pais_id,nombre,clave,continente) values (79,'Islandia','ISL','EUR');
insert into pais(pais_id,nombre,clave,continente) values (80,'Islas Åland','ALA','EUR');
insert into pais(pais_id,nombre,clave,continente) values (81,'Islas Feroe','FRO','EUR');
insert into pais(pais_id,nombre,clave,continente) values (82,'Italia','ITA','EUR');
insert into pais(pais_id,nombre,clave,continente) values (83,'Jersey','JEY','EUR');
insert into pais(pais_id,nombre,clave,continente) values (84,'Letonia','LVA','EUR');
insert into pais(pais_id,nombre,clave,continente) values (85,'Liechtenstein','LIE','EUR');
insert into pais(pais_id,nombre,clave,continente) values (86,'Lituania','LTU','EUR');
insert into pais(pais_id,nombre,clave,continente) values (87,'Luxemburgo','LUX','EUR');
insert into pais(pais_id,nombre,clave,continente) values (88,'Macedonia','MKD','EUR');
insert into pais(pais_id,nombre,clave,continente) values (89,'Malta','MLT','EUR');
insert into pais(pais_id,nombre,clave,continente) values (90,'Moldavia','MDA','EUR');
insert into pais(pais_id,nombre,clave,continente) values (91,'Mónaco','MCO','EUR');
insert into pais(pais_id,nombre,clave,continente) values (92,'Montenegro','MNE','EUR');
insert into pais(pais_id,nombre,clave,continente) values (93,'Noruega','NOR','EUR');
insert into pais(pais_id,nombre,clave,continente) values (94,'Países Bajos','NLD','EUR');
insert into pais(pais_id,nombre,clave,continente) values (95,'Polonia','POL','EUR');
insert into pais(pais_id,nombre,clave,continente) values (96,'Portugal','PRT','EUR');
insert into pais(pais_id,nombre,clave,continente) values (97,'Reino Unido','GBR','EUR');
insert into pais(pais_id,nombre,clave,continente) values (98,'República Checa','CZE','EUR');
insert into pais(pais_id,nombre,clave,continente) values (99,'Rumania','ROU','EUR');

