insert into tipo_serie(tipo_serie_id,clave,descripcion) values(1,'ACCION','Acción');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(2,'ANIMACIÓN','Animación');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(3,'AVENTURA','Aventura');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(4,'BIOGRAFÍA','Biografía');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(5,'CIENCIA FICCIÓN','Ciencia ficción');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(6,'COMEDIA','Comedia');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(7,'COMEDIA DRAMÁTICA','Comedia dramática');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(8,'CRIMEN','Crimen');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(9,'DRAMA','Drama');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(10,'ESPIONAJE','Espionaje');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(11,'FAMILIA','Familia');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(12,'FANTASÍA','Fantasía');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(13,'GUERRA','Guerra');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(14,'HISTÓRICO','Histórico');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(15,'JUDICIAL','Judicial');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(16,'MÉDICO','Médico');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(17,'ROMÁNTICO','Romántico');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(18,'SUSPENSE','Suspense');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(19,'TELESERIE','Teleserie');
insert into tipo_serie(tipo_serie_id,clave,descripcion) values(20,'TERROR','Terror');